name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: FranzDiebold/github-env-vars-action@v2.1.0

    - name: Build Start Discord Webhook
      uses: Poss111/discord-hook-action@v1.6.8
      with:
        discord-hook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
        title: 'Clash Bot Notification Lambda Deployment Notification'
        message: 'Starting Github build...'
        message-color: '15258703'

    - name: Check
      run : echo build $GITHUB_RUN_NUMBER

    - uses: actions/checkout@v2

    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install Dependencies
      run: npm i

    - name: Build Failed Discord Webhook
      uses: Poss111/discord-hook-action@v1.6.8
      if: ${{ failure() }}
      with:
        discord-hook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
        title: 'Clash Bot Notification Lambda Deployment Notification'
        message: 'Github build failed!'
        message-color: '16711680'

    - name: Build Succeded Discord Webhook
      uses: Poss111/discord-hook-action@v1.6.8
      if: ${{ success() && github.ref != 'refs/heads/master'}}
      with:
        discord-hook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
        title: 'Clash Bot Notification Lambda Deployment Notification'
        message: 'Github build succeeded!'
        message-color: '65345'

    - name: Deployment In Progress Discord Webhook
      uses: Poss111/discord-hook-action@v1.6.8
      if: ${{ success() && github.ref == 'refs/heads/master'}}
      with:
        discord-hook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
        title: 'Clash Bot Notification Lambda Deployment Notification'
        message: 'Deployment in progress...'
        message-color: '16750902'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      if: ${{ github.ref == 'refs/heads/master' }}
      with:
        aws-access-key-id: ${{ secrets.AWS_SECRET_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: us-east-1

    - name: Login to ECR
      id: login-ecr
      if: ${{ github.ref == 'refs/heads/master' }}
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push Clash-Bot image to Amazon ECR
      id: build-image
      if: ${{ github.ref == 'refs/heads/master' }}
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: poss11111/clash-bot-notification-lambda
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

    - name: Deploy to AWS CloudFormation
      if: ${{ github.ref == 'refs/heads/master' }}
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: ClashTimeLambdaStack
        template: ClashBotLambda.template
        parameter-overrides: "Image=${{ steps.build-image.outputs.image }}"

    - name: Deployment Failed Discord Webhook
      uses: Poss111/discord-hook-action@v1.6.8
      if: ${{ failure() && github.ref == 'refs/heads/master' }}
      with:
        discord-hook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
        title: 'Clash Bot Notification Lambda Deployment Notification'
        message: 'Deployment failed!'
        message-color: '16711680'

    - name: Deployment Succeeded Discord Webhook
      uses: Poss111/discord-hook-action@v1.6.8
      if: ${{ success() && github.ref == 'refs/heads/master' }}
      with:
        discord-hook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
        title: 'Clash Bot Notification Lambda Deployment Notification'
        message: 'Deployment succeeded!'
        message-color: '65345'
